---
mappings:
- alias: "ri.foundry.main.dataset.0323e581-5da7-4389-b467-1a2ca4b87276"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0323e581-5da7-4389-b467-1a2ca4b87276"
- alias: "ri.foundry.main.dataset.0ee18c8d-b489-4e0e-b147-295061f30646"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0ee18c8d-b489-4e0e-b147-295061f30646"
- alias: "ri.foundry.main.dataset.114a815f-2cdf-484e-8ea0-d232ada27938"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.114a815f-2cdf-484e-8ea0-d232ada27938"
- alias: "ri.foundry.main.dataset.1f8bac78-6260-4bed-9a5f-84b3f9bd4f88"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.1f8bac78-6260-4bed-9a5f-84b3f9bd4f88"
- alias: "ri.foundry.main.dataset.243c73f6-c63b-4a47-a729-61d4e3b24be0"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.243c73f6-c63b-4a47-a729-61d4e3b24be0"
- alias: "ri.foundry.main.dataset.2d6d60f9-f26e-433e-8ec4-d79193bf0b1f"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.2d6d60f9-f26e-433e-8ec4-d79193bf0b1f"
- alias: "ri.foundry.main.dataset.36abfcca-6f49-49f5-a71a-6d2fdfa43244"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.36abfcca-6f49-49f5-a71a-6d2fdfa43244"
- alias: "ri.foundry.main.dataset.3743b676-88c3-458c-9699-38abf93aac1a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3743b676-88c3-458c-9699-38abf93aac1a"
- alias: "ri.foundry.main.dataset.418ce0e1-c49f-445f-bc74-87b79fab7bfe"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.418ce0e1-c49f-445f-bc74-87b79fab7bfe"
- alias: "ri.foundry.main.dataset.4380414f-3551-4ad4-b17c-63e23cc7c4d0"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4380414f-3551-4ad4-b17c-63e23cc7c4d0"
- alias: "ri.foundry.main.dataset.48fb636f-3f26-4c1c-ac77-1b1e9306bb07"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.48fb636f-3f26-4c1c-ac77-1b1e9306bb07"
- alias: "ri.foundry.main.dataset.5185ea32-eba5-4d78-a131-8ae89b7de6ed"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5185ea32-eba5-4d78-a131-8ae89b7de6ed"
- alias: "ri.foundry.main.dataset.66b6e57c-dd68-4695-a022-d8e2982c1f27"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.66b6e57c-dd68-4695-a022-d8e2982c1f27"
- alias: "ri.foundry.main.dataset.70529c1d-1c5b-4a22-b263-cd8137e3572b"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.70529c1d-1c5b-4a22-b263-cd8137e3572b"
- alias: "ri.foundry.main.dataset.7ee226f1-8ada-48fe-a40e-2f7ad8db2faa"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7ee226f1-8ada-48fe-a40e-2f7ad8db2faa"
- alias: "ri.foundry.main.dataset.84845362-efbf-4923-8064-7b439be7271d"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.84845362-efbf-4923-8064-7b439be7271d"
- alias: "ri.foundry.main.dataset.918c6de9-88fb-4a26-990a-4de3402be5fe"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.918c6de9-88fb-4a26-990a-4de3402be5fe"
- alias: "ri.foundry.main.dataset.95a5b9e5-61d7-4557-976d-a83ea9434c81"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.95a5b9e5-61d7-4557-976d-a83ea9434c81"
- alias: "ri.foundry.main.dataset.a01b55f3-626d-459c-9d19-f65201df8ca5"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a01b55f3-626d-459c-9d19-f65201df8ca5"
- alias: "ri.foundry.main.dataset.a068fbd5-4dac-4592-bcfa-1f798233d5d0"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a068fbd5-4dac-4592-bcfa-1f798233d5d0"
- alias: "ri.foundry.main.dataset.a8155408-7f7d-4967-944d-3db60daeb81c"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a8155408-7f7d-4967-944d-3db60daeb81c"
- alias: "ri.foundry.main.dataset.af296d5e-9c0d-4854-b58c-f3bbf8cbfd28"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.af296d5e-9c0d-4854-b58c-f3bbf8cbfd28"
- alias: "ri.foundry.main.dataset.b1eb8321-d3ac-4065-bb16-260dee8a9dc1"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b1eb8321-d3ac-4065-bb16-260dee8a9dc1"
- alias: "ri.foundry.main.dataset.b25e529c-0940-4981-be8b-548133ec1d12"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b25e529c-0940-4981-be8b-548133ec1d12"
- alias: "ri.foundry.main.dataset.bb494767-5ea2-43e8-97d9-a6fddb9f63ba"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bb494767-5ea2-43e8-97d9-a6fddb9f63ba"
- alias: "ri.foundry.main.dataset.bc58902d-305f-47c0-8833-271da6a86b87"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bc58902d-305f-47c0-8833-271da6a86b87"
- alias: "ri.foundry.main.dataset.bfd0ff62-354f-40d8-811f-034443c500dc"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bfd0ff62-354f-40d8-811f-034443c500dc"
- alias: "ri.foundry.main.dataset.c4625196-f6bc-4840-bf49-b63b7e1390d0"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c4625196-f6bc-4840-bf49-b63b7e1390d0"
- alias: "ri.foundry.main.dataset.c5b24d93-aab2-479a-b216-36f10fcb3a12"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c5b24d93-aab2-479a-b216-36f10fcb3a12"
- alias: "ri.foundry.main.dataset.ca2e348b-7b80-44e6-9561-e9debc780782"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ca2e348b-7b80-44e6-9561-e9debc780782"
- alias: "ri.foundry.main.dataset.ca8fbbf5-2147-4686-a6c6-8423bfb97f3d"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.ca8fbbf5-2147-4686-a6c6-8423bfb97f3d"
- alias: "ri.foundry.main.dataset.cb8ec018-83b7-41ee-820a-e9e2f2f9fa06"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cb8ec018-83b7-41ee-820a-e9e2f2f9fa06"
- alias: "ri.foundry.main.dataset.d02069f4-5bbf-49bd-908a-b3a98b1fed76"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d02069f4-5bbf-49bd-908a-b3a98b1fed76"
- alias: "ri.foundry.main.dataset.d03145cc-e290-45f5-8606-9ed4716cb56d"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d03145cc-e290-45f5-8606-9ed4716cb56d"
- alias: "ri.foundry.main.dataset.d236153e-8f8a-4388-b667-041693e3d3b1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d236153e-8f8a-4388-b667-041693e3d3b1"
- alias: "ri.foundry.main.dataset.d6714d3d-952c-4ff4-90be-3caf7967aeff"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.d6714d3d-952c-4ff4-90be-3caf7967aeff"
- alias: "ri.foundry.main.dataset.da08b2ad-6c83-4def-8a66-99fba6375e1f"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.da08b2ad-6c83-4def-8a66-99fba6375e1f"
- alias: "ri.foundry.main.dataset.de6166c3-f8ab-4bf1-8f48-1e546f5065ef"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.de6166c3-f8ab-4bf1-8f48-1e546f5065ef"
- alias: "ri.foundry.main.dataset.e44ec721-b125-411a-a15b-b9c557b67343"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e44ec721-b125-411a-a15b-b9c557b67343"
- alias: "ri.foundry.main.dataset.eb978b5d-a334-45f9-aa96-3cf8c043b22a"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.eb978b5d-a334-45f9-aa96-3cf8c043b22a"
- alias: "ri.foundry.main.dataset.f69c73a9-ad6a-4906-805c-0e511d21bfba"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f69c73a9-ad6a-4906-805c-0e511d21bfba"
- alias: "ri.foundry.main.dataset.f9c387d2-0286-487f-b5ed-af499db4f4cd"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f9c387d2-0286-487f-b5ed-af499db4f4cd"
